{% set name = "django-slick-reporting" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-slick-reporting-{{ version }}.tar.gz
  sha256: 718ab3aa7692be531a35310e7e0bd5282613f310f8ac2e393ab6e6a080919766

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django >=2.2
    - python-dateutil >2.8.1
    - pytz
    - simplejson
    - django-crispy-forms
    - crispy-bootstrap4

test:
  imports:
    - slick_reporting
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://django-slick-reporting.com/
  summary: A one-stop report and analytics generation and computation with batteries included
  dev_url: https://github.com/ra-systems/django-slick-reporting
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
