{% set name = "django-slick-reporting" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-slick-reporting-{{ version }}.tar.gz
  sha256: 4afff1355231ca648acf7fc6c1714e404289d4ee63a4cc8479c8372014fa9b75

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=2.2
    - python-dateutil >2.8.1
    - pytz
    - simplejson
    - django-crispy-forms
    - crispy-bootstrap4

test:
  imports:
    - slick_reporting
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://django-slick-reporting.com/
  summary: A one-stop report and analytics generation and computation with batteries included
  dev_url: https://github.com/ra-systems/django-slick-reporting
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
